# Generated by Django 6.0.4 on 2026-05-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_emailverificationcode'),
        ('user', '0003_emailverificationcode'),
    ]

    operations = [
    ]
